image: gitlab.adeoweb.biz:8443/adeoweb/development-services/dpd/dpd-magento-2/php:72.3

build:
  stage: build
  script:
    - composer config --global repositories.magento composer https://repo.magento.com
    - composer config http-basic.repo.magento.com $COMPOSER_USER $COMPOSER_PASSWORD
    - composer config http-basic.gitlab.adeoweb.biz $GL_USER $GL_ACCESS_TOKEN
    - composer install --no-progress --optimize-autoloader
  artifacts:
    paths:
      - auth.json
      - composer.lock
      - vendor

test:
  stage: test
  script:
    - mkdir results
    - sleep 5
    - ./vendor/bin/phpcs --report=checkstyle --report-file=results/checkstyle.xml --report-\\Micheh\\PhpCodeSniffer\\Report\\Gitlab=results/phpcs-quality-report.json || true
    - ./vendor/bin/phpunit --log-junit=results/phpunit.xml
  artifacts:
    reports:
      junit: results/phpunit.xml
      codequality: results/phpcs-quality-report.json
