<div class="admin__field admin__field-option">
    <input type="checkbox" class="admin__control-checkbox" name="include_return_label"
           id="include_return_label_checkbox" value="0">

    <label class="admin__field-label" for="include_return_label_checkbox"><?php echo __('Include DPD Return Labels?'); ?></label>
</div>
<script>
    require([
        'jquery',
        'prototype',
        'Magento_Shipping/order/packaging',
    ], function(jQuery) {
        jQuery('#include_return_label_checkbox').on('change', function() {
            let dpdIncludeReturnLabels = 0;

            if (jQuery(this).is(':checked')) {
                dpdIncludeReturnLabels = 1;
            }

            window.packaging.setParamsCreateLabelRequest({'dpd_include_return_labels': dpdIncludeReturnLabels});
        });
    });
</script>
