<?php $shipment = $block->getShipment() ?>
<?php $order = $block->getOrder() ?>
<?php if ($shipment && $order) : ?>
    <?php $defaultShipmentItems = $shipment->getAllItems(); ?>
    <?php $dpdShipmentItems = $block->getShipmentItems(); ?>
    <?php $shipmentItems = $dpdShipmentItems ?: $defaultShipmentItems; ?>
    <table class="email-items">
        <thead>
        <tr>
            <th class="item-info">
                <?php echo $block->escapeHtml(__('Items')); ?>
            </th>
            <th class="item-qty">
                <?php echo $block->escapeHtml(__('Qty')); ?>
            </th>
        </tr>
        </thead>
        <?php foreach ($shipmentItems as $item) : ?>
            <?php if (!$item->getOrderItem()->getParentItem()) : ?>
                <tbody>
                <?php echo $block->getItemHtml($item); ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
