<?php /* @var \Magento\Framework\View\Element\Template $block */ ?>
<?php $shipment = $block->getShipment() ?>
<?php $viewModel = $block->getData('viewModel'); ?>
<?php
/* @var \Magento\Sales\Model\Order $_order */
$order = $block->getOrder() ?>
<!-- AdeoWeb Start -->
<?php if ($shipment && $order): ?>
    <?php $defaultTrackCollection = $order->getTracksCollection($shipment->getId()) ?>
    <?php $dpdTrackCollection = $block->getTracksCollection() ?>
    <?php $trackCollection = $dpdTrackCollection ?: $defaultTrackCollection; ?>
    <?php if ($trackCollection): ?>
        <br />
        <table class="shipment-track">
            <thead>
            <tr>
                <th><?= $block->escapeHtml(__('Shipped By')); ?></th>
                <th><?= $block->escapeHtml(__('Tracking Number')); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($trackCollection as $item): ?>
                <?php $trackingInfo = $viewModel->getTrackingInfoByTrackId((int)$item->getEntityId()); ?>
                <tr>
                    <td><?= $block->escapeHtml($item->getTitle()); ?>:</td>
                    <td>
                        <a href="<?= $block->escapeUrl(!empty($trackingInfo['url']) ? $trackingInfo['url'] : '');
                        ?>" target="_blank"><?= $block->escapeHtml($item->getNumber()); ?></a>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    <?php endif; ?>
<?php endif; ?>
